### ISSUE TITLE
player has bungee permission not working

### ISSUE THREAD

**Issue by antoinech2** [Skungee/Skungee#101]
Hello, I've an other problem with Skungee:

CODE:
```
command /test2 <text>:
	trigger:
		if bungee "%player%" has got bungee permission "%arg 1%":
			send "YES"
		else:
			send "NO"
```

ERROR:
```
02.11 20:16:09 [Server] ERROR #!#! 
02.11 20:16:09 [Server] ERROR #!#! [Skript] Severe Error:
02.11 20:16:09 [Server] ERROR #!#! 
02.11 20:16:09 [Server] ERROR #!#! Something went horribly wrong with Skript.
02.11 20:16:09 [Server] ERROR #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
02.11 20:16:09 [Server] ERROR #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
02.11 20:16:09 [Server] ERROR #!#! Here is full list of them:
02.11 20:16:09 [Server] ERROR #!#! skRayFall (https://sk.rayfall.net/) skript-mirror (https://github.com/btk5h/skript-mirror) Vixio (http://vixio.space) Skungee skUtilities (https://tim740.github.io/) SkQuery Skellett (https://forums.skunity.com/resources/skellett.24/) skript-db 
02.11 20:16:09 [Server] ERROR #!#! We could not identify which of those are specially related, so this might also be Skript issue.
02.11 20:16:09 [Server] ERROR #!#! You should try disabling those plugins one by one, trying to find which one causes it.
02.11 20:16:09 [Server] ERROR #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
02.11 20:16:09 [Server] ERROR #!#! In that case, you will be given instruction on how should you report it.
02.11 20:16:09 [Server] ERROR #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
02.11 20:16:09 [Server] ERROR #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
02.11 20:16:09 [Server] ERROR #!#! 
02.11 20:16:09 [Server] ERROR #!#! Stack trace:
02.11 20:16:09 [Server] ERROR #!#! java.lang.ClassCastException: java.util.HashSet cannot be cast to java.lang.Boolean
02.11 20:16:09 [Server] ERROR #!#!     at me.limeglass.skungee.spigot.elements.conditions.CondPlayerHasPermission.check(CondPlayerHasPermission.java:23)
02.11 20:16:09 [Server] ERROR #!#!     at ch.njol.skript.lang.Condition.run(Condition.java:56)
02.11 20:16:09 [Server] ERROR #!#!     at ch.njol.skript.lang.Conditional.walk(Conditional.java:51)
02.11 20:16:09 [Server] ERROR #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
02.11 20:16:09 [Server] ERROR #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
02.11 20:16:09 [Server] ERROR #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:292)
02.11 20:16:09 [Server] ERROR #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:251)
02.11 20:16:09 [Server] ERROR #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:251)
02.11 20:16:09 [Server] ERROR #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:168)
02.11 20:16:09 [Server] ERROR #!#!     at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35)
02.11 20:16:09 [Server] ERROR #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
02.11 20:16:09 [Server] ERROR #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
02.11 20:16:09 [Server] ERROR #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
02.11 20:16:09 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1484)
02.11 20:16:09 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297)
02.11 20:16:09 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
02.11 20:16:09 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
02.11 20:16:09 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
02.11 20:16:09 [Server] ERROR #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
02.11 20:16:09 [Server] ERROR #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
02.11 20:16:09 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
02.11 20:16:09 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)
02.11 20:16:09 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
02.11 20:16:09 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
02.11 20:16:09 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
02.11 20:16:09 [Server] ERROR #!#!     at java.lang.Thread.run(Thread.java:748)
02.11 20:16:09 [Server] ERROR #!#! 
02.11 20:16:09 [Server] ERROR #!#! Version Information:
02.11 20:16:09 [Server] ERROR #!#!   Skript: 2.4-beta9
02.11 20:16:09 [Server] ERROR #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
02.11 20:16:09 [Server] ERROR #!#!   Minecraft: 1.12.2
02.11 20:16:09 [Server] ERROR #!#!   Java: 1.8.0_181 (Java HotSpot(TM) 64-Bit Server VM 25.181-b13)
02.11 20:16:09 [Server] ERROR #!#!   OS: Linux amd64 4.9.87-xxxx-std-ipv6-64
02.11 20:16:09 [Server] ERROR #!#! 
02.11 20:16:09 [Server] ERROR #!#! Server platform: Paper
02.11 20:16:09 [Server] ERROR #!#! 
02.11 20:16:09 [Server] ERROR #!#! Current node: null
02.11 20:16:09 [Server] ERROR #!#! Current item: [Skungee] CondPlayerHasPermission- Syntax: [[bungee[[ ]cord]] [(player|uuid)] %string/player% (1¦(has|do[es])|2¦(has|do[es])(n't| not)) (have|got) [the] bungee[[ ]cord] permission[s] %strings%]
02.11 20:16:09 [Server] ERROR #!#! Current trigger: command /test2 (simple event) (test.sk, line -1)
02.11 20:16:09 [Server] ERROR #!#! 
02.11 20:16:09 [Server] ERROR #!#! Thread: Server thread
02.11 20:16:09 [Server] ERROR #!#! 
02.11 20:16:09 [Server] ERROR #!#! Language: english
02.11 20:16:09 [Server] ERROR #!#! Link parse mode: STRICT
02.11 20:16:09 [Server] ERROR #!#! 
02.11 20:16:09 [Server] ERROR #!#! End of Error.
02.11 20:16:09 [Server] ERROR #!#! 
```

Of course it's not working. How can I fix this?

**Comment by TheLimeGlass** [comment]
This is definitely not suppose to happen, can you provide your Skungee version and verify that both of the Skugee versions from Spigot and Bungee are the same.

**Comment by antoinech2** [comment]
Skungee version on bungee + 3 servers: 1.0.11 with lastest version of Skript (2.4-beta9)
All on the same port. Configuration is working because other Skungee's syntax are working properly.

Server-side config: [config.txt](https://github.com/Skungee/Skungee/files/3801399/config.txt)
Bungee-side config: [config.txt](https://github.com/Skungee/Skungee/files/3801400/config.txt)

**Comment by TheLimeGlass** [comment]
Fixed in recent versions.
