### ISSUE TITLE
Error while executing evaluate

### ISSUE THREAD

**Issue by antoinech2** [Skungee/Skungee#103]
CODE: 
```
function BungeeEvaluateAllServers(eval:text):
	loop all bungee servers:
		evaluate {_eval} on loop-value
BungeeEvaluateAllServers("broadcast ""This is a test""")
```

```
04.11 21:45:10 [Server] INFO [Skungee] [Skungee] Severe Error:
04.11 21:45:10 [Server] INFO [Skungee] Could not read incoming packet
04.11 21:45:10 [Server] INFO [Skungee] Something went wrong within Skungee.
04.11 21:45:10 [Server] INFO [Skungee] Please report this error to the developers of Skungee so we can fix this from happening in the future.
04.11 21:45:10 [Server] INFO [Skungee] Report this at https://github.com/TheLimeGlass/Skungee/issues
04.11 21:45:10 [Server] INFO [Skungee] You can also message one of the Skungee developers this error.
04.11 21:45:10 [Server] INFO [Skungee] Stack trace:
04.11 21:45:10 [Server] INFO [Skungee] java.net.SocketException: Relais brisé (pipe) (Write failed)
04.11 21:45:10 [Server] INFO [Skungee]     at java.net.SocketOutputStream.socketWrite0(Native Method)
04.11 21:45:10 [Server] INFO [Skungee]     at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
04.11 21:45:10 [Server] INFO [Skungee]     at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
04.11 21:45:10 [Server] INFO [Skungee]     at java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1877)
04.11 21:45:10 [Server] INFO [Skungee]     at java.io.ObjectOutputStream$BlockDataOutputStream.setBlockDataMode(ObjectOutputStream.java:1786)
04.11 21:45:10 [Server] INFO [Skungee]     at java.io.ObjectOutputStream.writeNonProxyDesc(ObjectOutputStream.java:1286)
04.11 21:45:10 [Server] INFO [Skungee]     at java.io.ObjectOutputStream.writeClassDesc(ObjectOutputStream.java:1231)
04.11 21:45:10 [Server] INFO [Skungee]     at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1427)
04.11 21:45:10 [Server] INFO [Skungee]     at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
04.11 21:45:10 [Server] INFO [Skungee]     at java.io.ObjectOutputStream.writeFatalException(ObjectOutputStream.java:1577)
04.11 21:45:10 [Server] INFO [Skungee]     at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:351)
04.11 21:45:10 [Server] INFO [Skungee]     at me.limeglass.skungee.spigot.sockets.SpigotRunnable.run(SpigotRunnable.java:103)
04.11 21:45:10 [Server] INFO [Skungee]     at java.lang.Thread.run(Thread.java:748)
04.11 21:45:10 [Server] INFO [Skungee] Information:
04.11 21:45:10 [Server] INFO [Skungee]   Skungee: 1.0.11
04.11 21:45:10 [Server] INFO [Skungee]   Bukkit: 1.12.2-R0.1-SNAPSHOT
04.11 21:45:10 [Server] INFO [Skungee]   Minecraft: v1_12_R1.
04.11 21:45:10 [Server] INFO [Skungee]   Java: 1.8.0_181 (Java HotSpot(TM) 64-Bit Server VM 25.181-b13)
04.11 21:45:10 [Server] INFO [Skungee]   OS: Linux amd64 4.9.87-xxxx-std-ipv6-64
04.11 21:45:10 [Server] INFO [Skungee] Running CraftBukkit: false
04.11 21:45:10 [Server] INFO [Skungee] Thread: Thread[Thread-102,5,main]
04.11 21:45:10 [Server] INFO [Skungee] End of Error.
```

However, the evaluate is executed!

**Comment by antoinech2** [comment]
Update: It is not a really important problem I think, the error disapear one day later...
