### ISSUE TITLE
Message

### ISSUE THREAD

**Issue by manze2709** [Skungee/Skungee#120]
Hello my code is 

send "ok" to bungee "%arg-1%"

i use skunge 1.0.11
whats the new syntax

**Comment by manze2709** [comment]
and it also came this error 


[17:47:50] [Craft Scheduler Thread - 340/WARN]: Exception in thread "Craft Scheduler Thread - 340" 
[17:47:50] [Craft Scheduler Thread - 340/WARN]: org.apache.commons.lang.UnhandledException: Plugin Skungee v1.0.11 generated an exception while executing task 410
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException

[18:00:43] [Craft Scheduler Thread - 365/WARN]: Exception in thread "Craft Scheduler Thread - 365" 
[18:00:43] [Craft Scheduler Thread - 365/WARN]: org.apache.commons.lang.UnhandledException: Plugin Skungee v1.0.11 generated an exception while executing task 410
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException

**Comment by TheLimeGlass** [comment]
This is the incorrect syntax, Skungee is thinking you're trying to send a player to a server, but this error shouldn't happen, can you also see if this error can be replicated on latest Spigot and Bungeecord?

**Comment by TheLimeGlass** [comment]
Duplicate #122
