### ISSUE TITLE
NullPointerException in EvtSwitchServer

### ISSUE THREAD

**Issue by TheLimeGlass** [Skungee/Skungee#137]
```
[23:10:41 ERROR]: #!#! [Skript] Severe Error:
[23:10:41 ERROR]: #!#! Could not load test.sk
[23:10:41 ERROR]: #!#!
[23:10:41 ERROR]: #!#! Something went horribly wrong with Skript.
[23:10:41 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[23:10:41 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[23:10:41 ERROR]: #!#! Here is full list of them:
[23:10:41 ERROR]: #!#! Skungee v1.0.12 SkQuery v3.6.5
[23:10:41 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[23:10:41 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[23:10:41 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[23:10:41 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[23:10:41 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[23:10:41 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[23:10:41 ERROR]: #!#!
[23:10:41 ERROR]: #!#! Stack trace:
[23:10:41 ERROR]: #!#! java.lang.NullPointerException
[23:10:41 ERROR]: #!#!     at me.limeglass.skungee.spigot.elements.events.EvtSwitchServer.toString(EvtSwitchServer.java:30)
[23:10:41 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:690)
[23:10:41 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:410)
[23:10:41 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:429)
[23:10:41 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:348)
[23:10:41 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:381)
[23:10:41 ERROR]: #!#!     at ch.njol.skript.Skript.reload(Skript.java:976)
[23:10:41 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:165)
[23:10:41 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[23:10:41 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[23:10:41 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:740)
[23:10:41 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchServerCommand(CraftServer.java:702)
[23:10:41 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:469)
[23:10:41 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431)
[23:10:41 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112)
[23:10:41 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934)
[23:10:41 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[23:10:41 ERROR]: #!#!
[23:10:41 ERROR]: #!#! Version Information:
[23:10:41 ERROR]: #!#!   Skript: 2.5-alpha1 (custom version)
[23:10:41 ERROR]: #!#!     Flavor: selfbuilt-unknown
[23:10:41 ERROR]: #!#!     Date: unknown
[23:10:41 ERROR]: #!#!   Bukkit: 1.15.2-R0.1-SNAPSHOT
[23:10:41 ERROR]: #!#!   Minecraft: 1.15.2
[23:10:41 ERROR]: #!#!   Java: 1.8.0_161 (Java HotSpot(TM) 64-Bit Server VM 25.161-b12)
[23:10:41 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[23:10:41 ERROR]: #!#!
[23:10:41 ERROR]: #!#! Server platform: Paper
[23:10:41 ERROR]: #!#!
[23:10:41 ERROR]: #!#! Current node: on player switch servers: (test.sk, line 14)
[23:10:41 ERROR]: #!#! Current item: null
[23:10:41 ERROR]: #!#!
[23:10:41 ERROR]: #!#! Thread: Server thread
[23:10:41 ERROR]: #!#!
[23:10:41 ERROR]: #!#! Language: english
[23:10:41 ERROR]: #!#! Link parse mode: DISABLED
[23:10:41 ERROR]: #!#!
[23:10:41 ERROR]: #!#! End of Error.
[23:10:41 ERROR]: #!#!
```
Caused when executing sk reload all. Using a modified Skript version based on 2.5-alpha1 not affecting this.

Could be anything in the test.sk script
```
on player switch servers:
	broadcast "&4testttttttttttt"
	broadcast "&4%event bungeecord player%"
	broadcast "&4%event bungeecord server%"
on bungeecord disconnect:
	broadcast "&ctest"
	broadcast "&c%event bungeecord player%"
	broadcast "&c%event bungeecord server%"
command /works:
	trigger:
		send skungee message "&aTesting works fine" to channel "Example"
on skungee message from "Example":
	broadcast skungee message
	broadcast skungee messages
```

**Comment by devilAPI** [comment]
same issue
