### ISSUE TITLE
Skungee loading issue 

### ISSUE THREAD

**Issue by ZeyKra** [Skungee/Skungee#139]
So my issue is when I launch my server all scripts load skungee connect but when I do and action that use skungee syntaxes Server send me that "An internal error occurred while attempting to perform this command.". So i searched for a long time how I can fix it finally I just reloaded all my scripts by /sk reload all and after I did that everything worked fine. The problem is that when I stop my server and launch it again it do the same things.  

When I was using v1.0.11 this issue wasn't here but since I updated to -> 1.0.13 I got that freakin issue

So for this issue I imagianed some supposition. maybe it's beacause scripts load before skungee so all scripts load before skungee's syntaxes.

btw i'm french so please be nice wit me 🇫🇷 

[My server logs.txt](https://github.com/Skungee/Skungee/files/4252682/My.server.logs.txt)

**Comment by ZeyKra** [comment]
![image](https://user-images.githubusercontent.com/42096409/75336484-88615500-588b-11ea-9cb8-e9a496bd6ecc.png)

also my bungee send me that

**Comment by ZeyKra** [comment]
new instruting error `[21:09:30] [Craft Scheduler Thread - 96/WARN]: Exception in thread "Craft Scheduler Thread - 96" 
[21:09:30] [Craft Scheduler Thread - 96/WARN]: org.apache.commons.lang.UnhandledException: Plugin Skungee v1.0.13 generated an exception while executing task 2314
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1469)
	at me.limeglass.skungee.spigot.sockets.PacketQueue$1.run(PacketQueue.java:63)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more`

![image](https://user-images.githubusercontent.com/42096409/75383589-ecf8d000-58dc-11ea-86a2-a1d929635ae1.png)

**Comment by ManuGooX** [comment]
This happened to me, try this version 1.0.10b and remove skungee folder in all your servers.

https://forums.skunity.com/resources/skungee-the-bungeecord-addon-for-skript.87/download?version=2035

**Comment by ZeyKra** [comment]
I did not have this issue when I used version 1.0.11

I updated my skungee version bc in the version 1.0.11 "current server of player"  was not working And i saw that 
![image](https://user-images.githubusercontent.com/42096409/75486129-454ad300-59ac-11ea-8d1e-45725125f397.png)

So i decided to update my skungee. Unfortunatly i got thoses error
