### ISSUE TITLE
Sending users error.

### ISSUE THREAD

**Issue by DebitCardz** [Skungee/Skungee#141]
```
[03:47:19 WARN]: [Skungee] Plugin Skungee v1.0.13 generated an exception while executing task 1414
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.remove(HashMap.java:1504) ~[?:?]
	at me.limeglass.skungee.spigot.sockets.PacketQueue$1.run(PacketQueue.java:66) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[server.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[server.jar:git-Paper-1618]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[server.jar:git-Paper-1618]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
[03:47:19 WARN]: [Skungee] Plugin Skungee v1.0.13 generated an exception while executing task 1412
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.remove(HashMap.java:1504) ~[?:?]
	at me.limeglass.skungee.spigot.sockets.PacketQueue$1.run(PacketQueue.java:66) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[server.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[server.jar:git-Paper-1618]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[server.jar:git-Paper-1618]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
[03:47:19 WARN]: [Skungee] Plugin Skungee v1.0.13 generated an exception while executing task 1422
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.remove(HashMap.java:1504) ~[?:?]
	at me.limeglass.skungee.spigot.sockets.PacketQueue$1.run(PacketQueue.java:66) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[server.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[server.jar:git-Paper-1618]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[server.jar:git-Paper-1618]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
[03:47:19 WARN]: [Skungee] Plugin Skungee v1.0.13 generated an exception while executing task 1421
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.remove(HashMap.java:1504) ~[?:?]
	at me.limeglass.skungee.spigot.sockets.PacketQueue$1.run(PacketQueue.java:66) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[server.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[server.jar:git-Paper-1618]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[server.jar:git-Paper-1618]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
[03:47:19 WARN]: [Skungee] Plugin Skungee v1.0.13 generated an exception while executing task 1411
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.remove(HashMap.java:1504) ~[?:?]
	at me.limeglass.skungee.spigot.sockets.PacketQueue$1.run(PacketQueue.java:66) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[server.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[server.jar:git-Paper-1618]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[server.jar:git-Paper-1618]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
[03:47:19 WARN]: [Skungee] Plugin Skungee v1.0.13 generated an exception while executing task 1626
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.remove(HashMap.java:1504) ~[?:?]
	at me.limeglass.skungee.spigot.sockets.PacketQueue$1.run(PacketQueue.java:66) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[server.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[server.jar:git-Paper-1618]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[server.jar:git-Paper-1618]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
```

This error appears whenever I attempt to move a player from one bungeecord server to another, Versions Paperspigot 1.12.2 latest and Skungee 1.0.13 with Skript 2.4.

**Comment by TheLimeGlass** [comment]
Duplicate https://github.com/Skungee/Skungee/issues/139
