### ISSUE TITLE
GlobalScripts Loading Error spams spigot console

### ISSUE THREAD

**Issue by mashmarvin** [Skungee/Skungee#143]
All was working fine when i used: Bungeecord (md_5) Build 1450, Spigot 1.8, Skungee 1.0.9, Skript 2.2-Fixes-V8b

I decided to update Bungeecord to newest 1487. Every Spigot console got spammed with following error every second:
```
[16:38:50] [Thread-15/WARN]: java.lang.NoSuchMethodError: ch.njol.skript.ScriptLoader.loadScripts([Lch/njol/skript/config/Config;)Lch/njol/skript/ScriptLoader$ScriptInfo;
[16:38:50] [Thread-15/WARN]:    at me.limeglass.skungee.spigot.sockets.SpigotPacketHandler.handlePacket(SpigotPacketHandler.java:167)
[16:38:50] [Thread-15/WARN]:    at me.limeglass.skungee.spigot.sockets.SpigotRunnable.run(SpigotRunnable.java:85)
[16:38:50] [Thread-15/WARN]:    at java.lang.Thread.run(Thread.java:748)
```

I tried using the latest version of Skungee (1.0.13) and nothing changed. So i switched back to Bungeecord 1450 and Skungee 1.0.9 but the error still remained.

Is there a compatible Skungee version for Spigot 1.8 and latest Bungeecord Build?

**Comment by mashmarvin** [comment]
Update:
I tried several Skungee versions now and are happy to say its fixed with 1.0.9.

I disabled a script in GlobalScripts folder (with a hyphen), after reenabling it it worked.

While trying 1.0.13 I got several nullPointerExceptions when setting or requesting network variables. Seems as this is the one thing not compatible with Spigot 1.8.
