### ISSUE TITLE
Skungee update bug

### ISSUE THREAD

**Issue by NikosDevMC** [Skungee/Skungee#149]
Hi!
Version: spigot 1.12.2
Skungee: Last version

When i updated skungee from 1.09 to 1.13, all of my skungee syntaxes broke
| Exemple:
send bungeecord player "%player%" to "Lobby"

`[15:42:24 INFO]: Nikos_s[/127.0.0.1:59912] logged in with entity id 46 at ([world]437.4497552016387, 207.0, -354.5101758687827)
[15:42:24 ERROR]: #!#!
[15:42:24 ERROR]: #!#! [Skript] Severe Error:
[15:42:24 ERROR]: #!#!
[15:42:24 ERROR]: #!#! Something went horribly wrong with Skript.
[15:42:24 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[15:42:24 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[15:42:24 ERROR]: #!#! Here is full list of them:
[15:42:24 ERROR]: #!#! skRayFall (https://sk.rayfall.net/) TuSKe (github.com/Tuke-Nuke/TuSKe) Skellett (https://forums.skunity.com/resources/skellett.24/) MundoSK (https://forums.skunity.com/resources/mundosk.69/) Reqn Skent SkriptJSON skript-mirror (https://github.com/btk5h/skript-mirror) Skungee SkStuff SkBee skUtilities (https://tim740.github.io/) SkQuery Ersatz
[15:42:24 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[15:42:24 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[15:42:24 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[15:42:24 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[15:42:24 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[15:42:24 ERROR]: #!#! Only if the author tells you to do so, report it as Skript issue (url below)
[15:42:24 ERROR]: #!#! Issue tracker: https://github.com/bensku/Skript/issues (only if you know what you're doing!)
[15:42:24 ERROR]: #!#!
[15:42:24 ERROR]: #!#! Stack trace:
[15:42:24 ERROR]: #!#! java.lang.NullPointerException
[15:42:24 ERROR]: #!#! at me.limeglass.skungee.spigot.elements.effects.EffConnectServer.execute(EffConnectServer.java:31)
[15:42:24 ERROR]: #!#! at ch.njol.skript.lang.Effect.run(Effect.java:52)
[15:42:24 ERROR]: #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[15:42:24 ERROR]: #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[15:42:24 ERROR]: #!#! at ch.njol.skript.effects.Delay$1.run(Delay.java:101)
[15:42:24 ERROR]: #!#! at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[15:42:24 ERROR]: #!#! at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
[15:42:24 ERROR]: #!#! at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
[15:42:24 ERROR]: #!#! at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[15:42:24 ERROR]: #!#! at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[15:42:24 ERROR]: #!#! at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[15:42:24 ERROR]: #!#! at java.lang.Thread.run(Unknown Source)
[15:42:24 ERROR]: #!#!
[15:42:24 ERROR]: #!#! Version Information:
[15:42:24 ERROR]: #!#! Skript: 2.2-dev32c (custom version)
[15:42:24 ERROR]: #!#! Bukkit: 1.12.2-R0.1-SNAPSHOT
[15:42:24 ERROR]: #!#! Minecraft: 1.12.2
[15:42:24 ERROR]: #!#! Java: 1.8.0_211 (Java HotSpot(TM) 64-Bit Server VM 25.211-b12)
[15:42:24 ERROR]: #!#! OS: Windows 10 amd64 10.0
[15:42:24 ERROR]: #!#!
[15:42:24 ERROR]: #!#! Running CraftBukkit: false
[15:42:24 ERROR]: #!#! Running Spigot (or compatible): true
[15:42:24 ERROR]: #!#! Running Paper (or compatible): false
[15:42:24 ERROR]: #!#!
[15:42:24 ERROR]: #!#! Current node: null
[15:42:24 ERROR]: #!#! Current item: [Skungee] EffConnectServer- Syntax: [[skungee] (send|connect) bungee[[ ]cord] [(player|uuid)] %strings/players% to [bungee[[ ]cord]] [server] %string% [with reason %-connectreason%], [skungee] (send|connect) [(player|uuid)] %strings/players% to [bungee[[ ]cord]] server %string% [with reason %-connectreason%]]
[15:42:24 ERROR]: #!#! Thread: Server thread
[15:42:24 ERROR]: #!#!
[15:42:24 ERROR]: #!#! Language: english
[15:42:24 ERROR]: #!#! Link parse mode: DISABLED
[15:42:24 ERROR]: #!#!
[15:42:24 ERROR]: #!#! End of Error.
[15:42:24 ERROR]: #!#!`

**Comment by mashmarvin** [comment]
Can confirm. Still happens on Spigot 1.12.2 with Skungee 1.0.15. After server start every Skungee syntax produces NullPointerException, until the specified script gets reloaded.

**Comment by Lotzyprod** [comment]
Confirmed on Spigot 1.14.4 and Spigot 1.15.2.
