### ISSUE TITLE
Error - CWBW.eu

### ISSUE THREAD

**Issue by Fazeris** [Skungee/Skungee#156]
[29.04 11:33:42.014] INFO: [Dev-1] [11:33:41 ERROR]: #!#!
[29.04 11:33:42.014] INFO: [Dev-1] [11:33:41 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[29.04 11:33:42.015] INFO: [Dev-1] [11:33:41 ERROR]: #!#! If you're a server admin however please go to http://dev.bukkit.org/server-mods/skript/tickets/
[29.04 11:33:42.015] INFO: [Dev-1] [11:33:41 ERROR]: #!#! and check whether this error has already been reported.
[29.04 11:33:42.015] INFO: [Dev-1] [11:33:41 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it,
[29.04 11:33:42.015] INFO: [Dev-1] [11:33:41 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[29.04 11:33:42.015] INFO: [Dev-1] [11:33:41 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[29.04 11:33:42.016] INFO: [Dev-1] [11:33:41 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[29.04 11:33:42.016] INFO: [Dev-1] [11:33:41 ERROR]: #!#!
[29.04 11:33:42.016] INFO: [Dev-1] [11:33:41 ERROR]: #!#! Stack trace:
[29.04 11:33:42.016] INFO: [Dev-1] [11:33:41 ERROR]: #!#! java.lang.NullPointerException
[29.04 11:33:42.016] INFO: [Dev-1] [11:33:41 ERROR]: #!#!     at me.limeglass.skungee.spigot.elements.effects.EffConnectServer.execute(EffConnectServer.java:31)
[29.04 11:33:42.017] INFO: [Dev-1] [11:33:41 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:50)
[29.04 11:33:42.017] INFO: [Dev-1] [11:33:41 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:63)
[29.04 11:33:42.017] INFO: [Dev-1] [11:33:41 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:91)
[29.04 11:33:42.017] INFO: [Dev-1] [11:33:41 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
[29.04 11:33:42.017] INFO: [Dev-1] [11:33:41 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand$1.call(ScriptCommand.java:220)
[29.04 11:33:42.017] INFO: [Dev-1] [11:33:41 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand$1.call(ScriptCommand.java:1)
[29.04 11:33:42.018] INFO: [Dev-1] [11:33:41 ERROR]: #!#!     at ch.njol.skript.util.Task.callSync(Task.java:139)
[29.04 11:33:42.018] INFO: [Dev-1] [11:33:41 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:193)
[29.04 11:33:42.018] INFO: [Dev-1] [11:33:41 ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:260)
[29.04 11:33:42.018] INFO: [Dev-1] [11:33:41 ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:155)
[29.04 11:33:42.018] INFO: [Dev-1] [11:33:41 ERROR]: #!#!     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[29.04 11:33:42.018] INFO: [Dev-1] [11:33:41 ERROR]: #!#!     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[29.04 11:33:42.019] INFO: [Dev-1] [11:33:41 ERROR]: #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[29.04 11:33:42.019] INFO: [Dev-1] [11:33:41 ERROR]: #!#!     at java.lang.reflect.Method.invoke(Method.java:498)
[29.04 11:33:42.019] INFO: [Dev-1] [11:33:41 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[29.04 11:33:42.019] INFO: [Dev-1] [11:33:41 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[29.04 11:33:42.019] INFO: [Dev-1] [11:33:41 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[29.04 11:33:42.019] INFO: [Dev-1] [11:33:41 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[29.04 11:33:42.020] INFO: [Dev-1] [11:33:41 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1154)
[29.04 11:33:42.020] INFO: [Dev-1] [11:33:41 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[29.04 11:33:42.020] INFO: [Dev-1] [11:33:41 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[29.04 11:33:42.020] INFO: [Dev-1] [11:33:41 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[29.04 11:33:42.020] INFO: [Dev-1] [11:33:41 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[29.04 11:33:42.020] INFO: [Dev-1] [11:33:41 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[29.04 11:33:42.021] INFO: [Dev-1] [11:33:41 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[29.04 11:33:42.021] INFO: [Dev-1] [11:33:41 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[29.04 11:33:42.021] INFO: [Dev-1] [11:33:41 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[29.04 11:33:42.021] INFO: [Dev-1] [11:33:41 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[29.04 11:33:42.021] INFO: [Dev-1] [11:33:41 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[29.04 11:33:42.021] INFO: [Dev-1] [11:33:41 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[29.04 11:33:42.022] INFO: [Dev-1] [11:33:41 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[29.04 11:33:42.022] INFO: [Dev-1] [11:33:41 ERROR]: #!#!
[29.04 11:33:42.022] INFO: [Dev-1] [11:33:41 ERROR]: #!#! Version Information:
[29.04 11:33:42.022] INFO: [Dev-1] [11:33:41 ERROR]: #!#!   Skript: 2.1.2
[29.04 11:33:42.022] INFO: [Dev-1] [11:33:41 ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[29.04 11:33:42.022] INFO: [Dev-1] [11:33:41 ERROR]: #!#!   Minecraft: 1.8.8
[29.04 11:33:42.022] INFO: [Dev-1] [11:33:41 ERROR]: #!#!   Java: 1.8.0_242
[29.04 11:33:42.022] INFO: [Dev-1] [11:33:41 ERROR]: #!#!
[29.04 11:33:42.022] INFO: [Dev-1] [11:33:41 ERROR]: #!#! Running CraftBukkit: false
[29.04 11:33:42.022] INFO: [Dev-1] [11:33:41 ERROR]: #!#!
[29.04 11:33:42.023] INFO: [Dev-1] [11:33:41 ERROR]: #!#! Current node: null
[29.04 11:33:42.023] INFO: [Dev-1] [11:33:41 ERROR]: #!#! Current item: [Skungee] EffConnectServer- Syntax: [[skungee] (send|connect) bungee[[ ]cord] [(player|uuid)[s]] %strings/players% to [bungee[[ ]cord]] [server[s]] %string% [with reason %-connectreason%], [skungee] (send|connect) [(player|uuid)[s]] %strings/players% to [bungee[[ ]cord]] server[s] %string% [with reason %-connectreason%]]
[29.04 11:33:42.023] INFO: [Dev-1] [11:33:41 ERROR]: #!#!
[29.04 11:33:42.023] INFO: [Dev-1] [11:33:41 ERROR]: #!#! Thread: Server thread
[29.04 11:33:42.023] INFO: [Dev-1] [11:33:41 ERROR]: #!#!
[29.04 11:33:42.023] INFO: [Dev-1] [11:33:41 ERROR]: #!#! End of Error.

**Comment by devilAPI** [comment]
I have the same problem :(

**Comment by TheLimeGlass** [comment]
Duplicate https://github.com/Skungee/Skungee/issues/149
