### ISSUE TITLE
I don't really know what this error is..

### ISSUE THREAD

**Issue by xeloamv** [Skungee/Skungee#157]
This is the errors, and i don't know how to fix it..

[SEVERE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@38af9828, id=0, owner=me.limeglass.skungee.bungeecord.Skungee@769a1df5, task=me.limeglass.skungee.bungeecord.managers.PlayerTimeManager$$Lambda$10/1885922916@376a0d86, delay=0, period=1000, running=true) encountered an exception
java.lang.NullPointerException
    at me.limeglass.skungee.bungeecord.managers.PlayerTimeManager.lambda$null$0(PlayerTimeManager.java:39)
    at java.lang.Iterable.forEach(Iterable.java:75)
    at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1082)
    at me.limeglass.skungee.bungeecord.managers.PlayerTimeManager.lambda$new$1(PlayerTimeManager.java:31)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)

**Comment by TheLimeGlass** [comment]
Duplicate https://github.com/Skungee/Skungee/issues/130
