### ISSUE TITLE
NPE if the BungeeCord can't connect to the Spigot/Paper server.

### ISSUE THREAD

**Issue by Zulfen** [Skungee/Skungee#167]
Hey there, Skungee has been working fine for me now. The only issue is that if it can't establish a connection to the Spigot server, it will throw an NPE, which will basically lock up the entire BungeeCord instance and won't allow players to connect:
```
>.... [14:45:33 ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@70ba695b, id=27, owner=me.limeglass.skungee.bungeecord.Skungee@aca68f16, task=me.limeglass.skungee.bungeecord.managers.PlayerTimeManager$$Lambda$193/0000000000DED7C0@2b11a0f2, delay=0, period=1000, running=true) encountered an exception
java.lang.NullPointerException: null
at me.limeglass.skungee.bungeecord.managers.PlayerTimeManager.lambda$null$0(PlayerTimeManager.java:39) ~[?:?]
at me.limeglass.skungee.bungeecord.managers.PlayerTimeManager$$Lambda$194.00000000440053D0.accept(Unknown Source) ~[?:?]
at java.lang.Iterable.forEach(Unknown Source) ~[?:1.8.0_232]
at java.util.Collections$UnmodifiableCollection.forEach(Unknown Source) ~[?:1.8.0_232]
at me.limeglass.skungee.bungeecord.managers.PlayerTimeManager.lambda$new$1(PlayerTimeManager.java:31) ~[?:?]
at me.limeglass.skungee.bungeecord.managers.PlayerTimeManager$$Lambda$193.0000000000DED7C0.run(Unknown Source) ~[?:?]
at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66) ~[server.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:1.8.0_232]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:1.8.0_232]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_232]
```
If you need any more information, please don't hesitate to ask :)

Just noticed that this also occurs everytime anyone connects for the first time after a restart. After this, it doesn't appear to occur again.

**Comment by Zulfen** [comment]
I am using Waterfall-346 here by the way and the latest version of Skungee.
