### ISSUE TITLE
Error with the new compatible Skungee version

### ISSUE THREAD

**Issue by Hypenexy** [Skungee/Skungee#179]
When I start BungeeCord this error appears. Tried deleting the old config file, didn't help.

[WARNING] Exception encountered when loading plugin: Skungee
java.lang.NoClassDefFoundError: com/sitrica/japson/server/JapsonServer
    at com.skungee.bungeecord.BungeeSkungee.onEnable(BungeeSkungee.java:70)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:250)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:286)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: com.sitrica.japson.server.JapsonServer
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:63)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:37)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 5 more

**Comment by TheLimeGlass** [comment]
Did you compile it yourself? Did you get the download from the releases page on the 2.0.0 repo? Please use the 2.0.0 issues tab for 2.0.0 related issues.

**Comment by Hypenexy** [comment]
I think this error happened on 1.0.14

**Comment by Hypenexy** [comment]
Could someone tell me how can I run gradle shadow? I really am new here. And also yes I tried gradlew.bat since I am on my Windows pc rn.

**Comment by Lythed** [comment]
Hi, I have the exact same issue. I have no idea why this error is thrown.

Some informations, hope I will help you a bit:

localhost
Bungeecord version is a fork, FlameCord 0.2.5 (I can give you my config files if needed)
Skungee version is the latest from the release page (1.0.14) I dit not compile it myself
There is no other plugins or old configuration file, this is a fresh install
```
[01:46:02 INFO]: Using standard Java JCE cipher. 

[01:46:02 INFO]: Using standard Java compressor. 

[01:46:02 INFO]: Enabled FlameCord version 0.2.5 SNAPSHOT

[01:46:02 INFO]: Loaded plugin Skungee version 2.0.0-ALPHA-2 by Skungee 

[01:46:02 WARN]: Forced host server pvp is not defined 

[01:46:03 WARN]: Exception encountered when loading plugin: Skungee 
java.lang.NoClassDefFoundError: com/sitrica/japson/server/JapsonServer
        at com.skungee.bungeecord.BungeeSkungee.onEnable(BungeeSkungee.java:70) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:262) ~[FlameCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:334) ~[FlameCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:63) ~[FlameCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[FlameCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
Caused by: java.lang.ClassNotFoundException: com.sitrica.japson.server.JapsonServer
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53) ~[FlameCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27) ~[FlameCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        ... 5 more

[01:46:03 INFO]: Listening on /0.0.0.0:25565
```

**Comment by TheLimeGlass** [comment]
You need to type `gradle clean shadow` This will shade in the Japson library. Please make any new issues on https://github.com/Skungee/Skungee-2.0.0/issues relating to 2.0.0, and I can assist you there.

**Comment by Hypenexy** [comment]
Odd question but did you accidentally upload 2.0.0 version to 1.0.14 github or is 1.0.14 the new Skungee 2.0.0 and if that's the case can we get 1.16 bungeecord fix for 1v?

**Comment by OneYellowLemon** [comment]
@TheLimeGlass It does appear that you uploaded the wrong version. Can you confirm?

**Comment by TheLimeGlass** [comment]
> 
> 
> @TheLimeGlass It does appear that you uploaded the wrong version (2.0.0 instead of 1.0.14). I just cloned and built it and it has a different file size and doesn't error out on loading. It also says it is version 1.0.14 in console

Skungee 2.0.0 is at https://github.com/Skungee/Skungee-2.0.0

**Comment by OneYellowLemon** [comment]
No no no this release is actually the 2.0.0 jar
https://github.com/Skungee/Skungee/releases/tag/1.0.14

**Comment by OneYellowLemon** [comment]
Downloading that jar which is supposedly 1.0.14 and running it shows that it is actually 2.0.0 and errors out

**Comment by OneYellowLemon** [comment]
@TheLimeGlass Does that make sense?

**Comment by OneYellowLemon** [comment]
@TheLimeGlass This still hasn't been fixed, could you please compile 1.0.14 again and upload it. The file you uploaded a few days ago isn't 1.0.14

**Comment by TheLimeGlass** [comment]
Download 1.0.14 on the GitHub, it's 1.0.14 for me. The 2.0.0 repository is different than just the Skungee one.

**Comment by OneYellowLemon** [comment]
Huh, I redownloaded from [](https://github.com/Skungee/Skungee/releases/tag/1.0.14) it seems to be working now. That's very odd as I checked three times & redownloaded, but it is loading properly and reporting it is 1.0.14. Oh well, I might just be a big stupid. Thanks for the help!
