### ISSUE TITLE
SkungeeMessageEvent may only be triggered asynchronously.

### ISSUE THREAD

**Issue by coookiemonsterm** [Skungee/Skungee#194]
`[07:01:47 WARN]: [Skungee] Task #4555 for Skungee v1.0.15 generated an exception
java.lang.IllegalStateException: SkungeeMessageEvent may only be triggered asynchronously.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:593) ~[patched_1.15.2.jar:git-Paper-379]
        at me.limeglass.skungee.spigot.sockets.SpigotPacketHandler.lambda$handlePacket$6(SpigotPacketHandler.java:216) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Paper-379]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.15.2.jar:git-Paper-379]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1264) ~[patched_1.15.2.jar:git-Paper-379]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-379]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181) ~[patched_1.15.2.jar:git-Paper-379]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970) ~[patched_1.15.2.jar:git-Paper-379]
        at java.lang.Thread.run(Thread.java:834) [?:?]
`

Bungeecord Jar: FlameCord
Paper version git-Paper-379 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by TheLimeGlass** [comment]
duplicate https://github.com/Skungee/Skungee/issues/183
