### ISSUE TITLE
No bungee messages working at all

### ISSUE THREAD

**Issue by melinstagibson** [Skungee/Skungee#195]
So i get this error whenever i try any kind of messaging a player on bungeecord
```[09:39:07 ERROR]: #!#!
[09:39:07 ERROR]: #!#! [Skript] Severe Error:
[09:39:07 ERROR]: #!#!
[09:39:07 ERROR]: #!#! You're running outdated version of Skript! Please try updating it NOW; it might fix this.
[09:39:07 ERROR]: #!#! Run /sk update check to get a download link to latest Skript!
[09:39:07 ERROR]: #!#! You will be given instructions how to report this error if it persists after update.
[09:39:07 ERROR]: #!#!
[09:39:07 ERROR]: #!#! Stack trace:
[09:39:07 ERROR]: #!#! java.lang.NullPointerException
[09:39:07 ERROR]: #!#!     at me.limeglass.skungee.spigot.elements.effects.EffMessagePlayers.execute(EffMessagePlayers.java:23)
[09:39:07 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[09:39:07 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[09:39:07 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[09:39:07 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[09:39:07 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:292)
[09:39:07 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:251)
[09:39:07 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:195)
[09:39:07 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[09:39:07 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[09:39:07 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794)
[09:39:07 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchServerCommand(CraftServer.java:756)
[09:39:07 ERROR]: #!#!     at net.minecraft.server.v1_16_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:411)
[09:39:07 ERROR]: #!#!     at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:378)
[09:39:07 ERROR]: #!#!     at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212)
[09:39:07 ERROR]: #!#!     at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000)
[09:39:07 ERROR]: #!#!     at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[09:39:07 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[09:39:07 ERROR]: #!#!
[09:39:07 ERROR]: #!#! Version Information:
[09:39:07 ERROR]: #!#!   Skript: 2.5-alpha6(rev1) (OUTDATED)
[09:39:07 ERROR]: #!#!     Flavor: skriptlang-github
[09:39:07 ERROR]: #!#!     Date: 2020-07-21
[09:39:07 ERROR]: #!#!   Bukkit: 1.16.1-R0.1-SNAPSHOT
[09:39:07 ERROR]: #!#!   Minecraft: 1.16.1
[09:39:07 ERROR]: #!#!   Java: 1.8.0_171 (OpenJDK 64-Bit Server VM 25.171-b11)
[09:39:07 ERROR]: #!#!   OS: Linux amd64 4.10.0-40-generic
[09:39:07 ERROR]: #!#!
[09:39:07 ERROR]: #!#! Server platform: Paper
[09:39:07 ERROR]: #!#!
[09:39:07 ERROR]: #!#! Current node: null
[09:39:07 ERROR]: #!#! Current item: [Skungee] EffMessagePlayers- Syntax: [[skungee] (message|send|msg) %strings% to [(all [[of] the]|the)] bungee[[ ][cord]] players]
[09:39:07 ERROR]: #!#! Current trigger: command /proxytest (simple event) (proxyvote.sk, line -1)
[09:39:07 ERROR]: #!#!
[09:39:07 ERROR]: #!#! Thread: Server thread
[09:39:07 ERROR]: #!#!
[09:39:07 ERROR]: #!#! Language: english
[09:39:07 ERROR]: #!#! Link parse mode: DISABLED
[09:39:07 ERROR]: #!#!
[09:39:07 ERROR]: #!#! End of Error.
[09:39:07 ERROR]: #!#!
```

and direct messages stopped working aswell
`Can't understand this condition/effect: send "t" to bungee "Mel_InstaGibson" (proxyvote.sk, line 35: send "t" to bungee "Mel_InstaGibson"')`

Skript:
```
command /proxytest:
        permission: *
        trigger:
#               if bungee "mel_instagibson" is online:
#                       send "online"
                send "t" to bungee "Mel_InstaGibson"
                send "test" to all bungee players
```
im on the latest skungee, paperspigot 1.16.1 and Skript version

**Comment by EgidioBezerra** [comment]
I'm having almost the same issue but with Skungee Message instead of Bungee Message Player,

`[14:01:41 ERROR]: [Skript] Can't understand this condition/effect: send Skungee message argument to "Spawn" (Skungee.sk, line 3: send Skungee message argument to "Spawn"')
[14:01:41 ERROR]: [Skript] Can't understand this condition/effect: send Skungee message argument to "Mina" (Skungee.sk, line 4: send Skungee message argument to "Mina"')
[14:01:41 ERROR]: [Skript] Can't understand this condition/effect: send Skungee message argument to "Pandora" (Skungee.sk, line 5: send Skungee message argument to "Pandora"')`

**Comment by TheLimeGlass** [comment]
You're inputting a value that is not set
