### ISSUE TITLE
No Bungee send server

### ISSUE THREAD

**Issue by Ori5000** [Skungee/Skungee#196]
Hey so I'm using Skungee 1.0.15 and skript 2.2-dev36 (bensku), my server is based 1.8
and I got an error everytime I trying to use this effect.

`[18:11:55 ERROR]: #!#!
[18:11:55 ERROR]: #!#! [Skript] Severe Error:
[18:11:55 ERROR]: #!#!
[18:11:55 ERROR]: #!#! Something went horribly wrong with Skript.
[18:11:55 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[18:11:55 ERROR]: #!#! Your Minecraft version or server software appears to be unsupported by Skript (bensku's version).
[18:11:55 ERROR]: #!#! Currently only supported servers are Spigot and its forks for Minecraft 1.9 or newer.
[18:11:55 ERROR]: #!#! Other versions might work, but since you're getting this error message something is NOT working,
[18:11:55 ERROR]: #!#! nor it will work, unless you switch to supported platform.
[18:11:55 ERROR]: #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues (only if you know what you're doing!)
[18:11:55 ERROR]: #!#!
[18:11:55 ERROR]: #!#! Stack trace:
[18:11:55 ERROR]: #!#! java.lang.NullPointerException
[18:11:55 ERROR]: #!#!     at me.limeglass.skungee.spigot.elements.effects.EffConnectServer.execute(EffConnectServer.java:31)
[18:11:55 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[18:11:55 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[18:11:55 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[18:11:55 ERROR]: #!#!     at com.github.tukenuke.tuske.util.EffectSection.runSection(EffectSection.java:135)
[18:11:55 ERROR]: #!#!     at com.github.tukenuke.tuske.sections.gui.EffFormatGUI.lambda$execute$1(EffFormatGUI.java:146)
[18:11:55 ERROR]: #!#!     at com.github.tukenuke.tuske.manager.gui.GUI.run(GUI.java:31)
[18:11:55 ERROR]: #!#!     at com.github.tukenuke.tuske.manager.gui.GUIManager$1.onClick(GUIManager.java:149)
[18:11:55 ERROR]: #!#!     at com.github.tukenuke.tuske.listeners.GUIListener.onEvent(GUIListener.java:57)
[18:11:55 ERROR]: #!#!     at com.github.tukenuke.tuske.manager.gui.v2.SkriptGUIEvent.check(SkriptGUIEvent.java:39)
[18:11:55 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:145)
[18:11:55 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:109)
[18:11:55 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[18:11:55 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[18:11:55 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[18:11:55 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1630)
[18:11:55 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31)
[18:11:55 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9)
[18:11:55 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[18:11:55 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[18:11:55 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[18:11:55 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[18:11:55 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[18:11:55 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[18:11:55 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[18:11:55 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[18:11:55 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[18:11:55 ERROR]: #!#!
[18:11:55 ERROR]: #!#! Version Information:
[18:11:55 ERROR]: #!#!   Skript: 2.2-dev36
[18:11:55 ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[18:11:55 ERROR]: #!#!   Minecraft: 1.8.8
[18:11:55 ERROR]: #!#!   Java: 1.8.0_261 (Java HotSpot(TM) 64-Bit Server VM 25.261-b12)
[18:11:55 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[18:11:55 ERROR]: #!#!
[18:11:55 ERROR]: #!#! Server platform: Spigot
[18:11:55 ERROR]: #!#!
[18:11:55 ERROR]: #!#! Current node: null
[18:11:55 ERROR]: #!#! Current item: [Skungee] EffConnectServer- Syntax: [[skungee] (send|connect) bungee[[ ]cord] [(player|uuid)[s]] %strings/players% to [bungee[[ ]cord]] [server[s]] %string% [with reason %-connectreason%], [skungee] (send|connect) [(player|uuid)[s]] %strings/players% to [bungee[[ ]cord]] server[s] %string% [with reason %-connectreason%]]
[18:11:55 ERROR]: #!#!
[18:11:55 ERROR]: #!#! Thread: Server thread
[18:11:55 ERROR]: #!#!
[18:11:55 ERROR]: #!#! Language: english
[18:11:55 ERROR]: #!#! Link parse mode: DISABLED
[18:11:55 ERROR]: #!#!
[18:11:55 ERROR]: #!#! End of Error.
[18:11:55 ERROR]: #!#!`

Skript:
```command /games:
  trigger:
    open virtual chest inventory with size 1 named "             &8» &6Game Menu &8«" to player
    format gui slot 2 of player with diamond pickaxe of efficiency 1 named "&8» &6The Bridge &8«" with lore "&6Click to connect The Bridge" to run:
      connect bungee player to bungee server "bridge"
    format gui slot 4 of player with iron sword named "&8» &6FFA &8«" with lore "&6Click to connect FFA" to run:
      connect bungee player to bungee server "ffa"
      send "&aConnecting..." to player
    format gui slot 6 of player with water_bottle:16421 named "&8» &6PRACTICE &8«" with lore "&6Click to connect Practice" to run:
      connect bungee player to bungee server "practice"
      send "&aConnecting..." to player```

**Comment by TheLimeGlass** [comment]
Duplicate #149
