### ISSUE TITLE
Not Bungee Send connect

### ISSUE THREAD

**Issue by iNaruse** [Skungee/Skungee#197]
`[02:37:58] [Server thread/ERROR]: #!#!
[02:37:58] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[02:37:58] [Server thread/ERROR]: #!#!
[02:37:58] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[02:37:58] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[02:37:58] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[02:37:58] [Server thread/ERROR]: #!#! Here is full list of them:
[02:37:58] [Server thread/ERROR]: #!#! skRayFall (https://sk.rayfall.net/) Skungee TuSKe (github.com/Tuke-Nuke/TuSKe) SK-NBeeT (https://github.com/ShaneBeee/Sk-NBeeT) skUtilities (https://tim740.github.io/) SkQuery SkChoke DiscordSRV (https://github.com/DiscordSRV/DiscordSRV)
[02:37:58] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[02:37:58] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[02:37:58] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[02:37:58] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[02:37:58] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[02:37:58] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[02:37:58] [Server thread/ERROR]: #!#!
[02:37:58] [Server thread/ERROR]: #!#! Stack trace:
[02:37:58] [Server thread/ERROR]: #!#! java.lang.NullPointerException
[02:37:58] [Server thread/ERROR]: #!#!     at me.limeglass.skungee.spigot.elements.effects.EffConnectServer.execute(EffConnectServer.java:31)
[02:37:58] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[02:37:58] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[02:37:58] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[02:37:58] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[02:37:58] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:156)
[02:37:58] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:114)
[02:37:58] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[02:37:58] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529)
[02:37:58] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514)
[02:37:58] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2147)
[02:37:58] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32)
[02:37:58] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10)
[02:37:58] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
[02:37:58] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
[02:37:58] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
[02:37:58] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[02:37:58] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
[02:37:58] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918)
[02:37:58] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911)
[02:37:58] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127)
[02:37:58] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895)
[02:37:58] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828)
[02:37:58] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[02:37:58] [Server thread/ERROR]: #!#!
[02:37:58] [Server thread/ERROR]: #!#! Version Information:
[02:37:58] [Server thread/ERROR]: #!#!   Skript: 2.4.1 (latest)
[02:37:58] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[02:37:58] [Server thread/ERROR]: #!#!     Date: 2019-12-22
[02:37:58] [Server thread/ERROR]: #!#!   Bukkit: 1.15.2-R0.1-SNAPSHOT
[02:37:58] [Server thread/ERROR]: #!#!   Minecraft: 1.15.2
[02:37:58] [Server thread/ERROR]: #!#!   Java: 1.8.0_261 (Java HotSpot(TM) 64-Bit Server VM 25.261-b12)
[02:37:58] [Server thread/ERROR]: #!#!   OS: Windows 10 amd64 10.0
[02:37:58] [Server thread/ERROR]: #!#!
[02:37:58] [Server thread/ERROR]: #!#! Server platform: Spigot
[02:37:58] [Server thread/ERROR]: #!#!
[02:37:58] [Server thread/ERROR]: #!#! Current node: null
[02:37:58] [Server thread/ERROR]: #!#! Current item: [Skungee] EffConnectServer- Syntax: [[skungee] (send|connect) bungee[[ ]cord] [(player|uuid)[s]] %strings/players% to [bungee[[ ]cord]] [server[s]] %string% [with reason %-connectreason%], [skungee] (send|connect) [(player|uuid)[s]] %strings/players% to [bungee[[ ]cord]] server[s] %string% [with reason %-connectreason%]]
[02:37:58] [Server thread/ERROR]: #!#! Current trigger: inventory click (dispense/spawn/drop/craft/pickup/consume/break/despawn/merge) (메뉴.sk, line 11)
[02:37:58] [Server thread/ERROR]: #!#!
[02:37:58] [Server thread/ERROR]: #!#! Thread: Server thread
[02:37:58] [Server thread/ERROR]: #!#!
[02:37:58] [Server thread/ERROR]: #!#! Language: english
[02:37:58] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[02:37:58] [Server thread/ERROR]: #!#!
[02:37:58] [Server thread/ERROR]: #!#! End of Error.
[02:37:58] [Server thread/ERROR]: #!#!`

**Comment by TheLimeGlass** [comment]
Duplicate #149
