### ISSUE TITLE
Unknown host

### ISSUE THREAD

**Issue by daffyyyy** [Skungee/Skungee#211]
```
[23:19:32 INFO]: [Skungee] Connected to server survival with port 25567
[23:19:32 INFO]: 
[23:19:32 INFO]: [Skungee] [Skungee] Severe Error: [Unknown host: /xxx:25567]
[23:19:32 INFO]: 
[23:19:32 INFO]: [Skungee] Something went wrong within Skungee.
[23:19:32 INFO]: [Skungee] Please report this error to the developers of Skungee so we can fix this from happening in the future.
[23:19:32 INFO]: 
[23:19:32 INFO]: [Skungee] Report this at https://github.com/TheLimeGlass/Skungee/issues. You can also message one of the Skungee developers.
[23:19:32 INFO]: 
[23:19:32 INFO]: [Skungee] Stack trace:
[23:19:32 INFO]: [Skungee] java.net.UnknownHostException: f8a35eaa-3371-4a3f-8d57-b008a19ba439: f8a35eaa-3371-4a3f-8d57-b008a19ba439: Name or service not known
[23:19:32 INFO]: [Skungee]     at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1626)
[23:19:32 INFO]: [Skungee]     at me.limeglass.skungee.bungeecord.handlers.HeartbeatHandler.handlePacket(HeartbeatHandler.java:39)
[23:19:32 INFO]: [Skungee]     at me.limeglass.skungee.bungeecord.sockets.BungeeRunnable.run(BungeeRunnable.java:118)
[23:19:32 INFO]: [Skungee]     at java.base/java.lang.Thread.run(Thread.java:830)
[23:19:32 INFO]: [Skungee] Caused by: java.net.UnknownHostException: f8a35eaa-3371-4a3f-8d57-b008a19ba439: Name or service not known
[23:19:32 INFO]: [Skungee]     at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
[23:19:32 INFO]: [Skungee]     at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:930)
[23:19:32 INFO]: [Skungee]     at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1499)
[23:19:32 INFO]: [Skungee]     at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:849)
[23:19:32 INFO]: [Skungee]     at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1489)
[23:19:32 INFO]: [Skungee]     at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1621)
[23:19:32 INFO]: [Skungee]     at me.limeglass.skungee.bungeecord.handlers.HeartbeatHandler.handlePacket(HeartbeatHandler.java:39)
[23:19:32 INFO]: [Skungee]     at me.limeglass.skungee.bungeecord.sockets.BungeeRunnable.run(BungeeRunnable.java:118)
[23:19:32 INFO]: [Skungee]     at java.base/java.lang.Thread.run(Thread.java:830)
[23:19:32 INFO]: 
[23:19:32 INFO]: [Skungee] Information:
[23:19:32 INFO]: [Skungee]   Skungee: 1.0.15
[23:19:32 INFO]: [Skungee]   Bungee: 0.4.3
[23:19:32 INFO]: [Skungee]   Game version: 1.7.x-1.16.x
[23:19:32 INFO]: [Skungee]   Protocol version: 753
[23:19:32 INFO]: [Skungee]   Java: 13.0.2 (OpenJDK 64-Bit Server VM 13.0.2+8)
[23:19:32 INFO]: [Skungee]   OS: Linux amd64 5.9.0-rt16-xanmod2
[23:19:32 INFO]: 
[23:19:32 INFO]: [Skungee] Thread: Thread[Thread-24,5,Skungee]
[23:19:32 INFO]: [Skungee] Cause: [Unknown host: /xxx:25567]
[23:19:32 INFO]: 
[23:19:32 INFO]: [Skungee] End of Error.
```
with servers on separate machines :/

**Comment by TheLimeGlass** [comment]
What are you putting in the host option? It must be an ip address.
