### ISSUE TITLE
Timeout-Error spamming console

### ISSUE THREAD

**Issue by brobie1kanobi** [Skungee/Skungee#216]
This error keep spamming my console after updating to the latest version:

```
[13:12:49 WARN]: java.util.concurrent.TimeoutException
[13:12:49 WARN]:        at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1784)
[13:12:49 WARN]:        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
[13:12:49 WARN]:        at com.sitrica.japson.shared.Japson.sendPacket(Japson.java:190)
[13:12:49 WARN]:        at com.sitrica.japson.client.JapsonClient.sendPacket(JapsonClient.java:150)
[13:12:49 WARN]:        at com.skungee.spigot.tasks.ServerDataTask.run(ServerDataTask.java:28)
[13:12:49 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
[13:12:49 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[13:12:49 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:12:49 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[13:12:49 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[13:12:49 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

Skungee worked fine before with no errors, changed nothing but the jar file and this started happening. Also, here is the printout of the version just to verify:

```
[13:13:05 INFO]: Skungee version 2.0.0-ALPHA-9
[13:13:05 INFO]: Author: Skungee
```
Other notables: I am running the latest version of Skript (2.5.1), the latest Paper (paper-260) as well as the latest Bungeecord.

**Comment by brobie1kanobi** [comment]
Closing issue as I neglected to update my bungee servers jar file. Sorry for this..
