### ISSUE TITLE
when i try to use my command i get these error

### ISSUE THREAD

**Issue by silvercreeper356** [Skungee/Skungee#234]
heres my script that causes the error when i execute the command
command /hub:
        permission: hub
        Permission message: "&cNo permission."
        Trigger:
                skungee send event-player to bungeecord server "hub"

thats the only script that i have on that server

[17:22:58 ERROR]: #!#! 
[17:22:58 ERROR]: #!#! [Skript] Severe Error:
[17:22:58 ERROR]: #!#! 
[17:22:58 ERROR]: #!#! Something went horribly wrong with Skript.
[17:22:58 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[17:22:58 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[17:22:58 ERROR]: #!#! Here is full list of them:
[17:22:58 ERROR]: #!#! Skungee v1.0.15 SkQuery v4.1.4 
[17:22:58 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[17:22:58 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[17:22:58 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[17:22:58 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[17:22:58 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[17:22:58 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[17:22:58 ERROR]: #!#! 
[17:22:58 ERROR]: #!#! Stack trace:
[17:22:58 ERROR]: #!#! java.lang.NullPointerException
[17:22:58 ERROR]: #!#!     at me.limeglass.skungee.spigot.elements.effects.EffConnectServer.execute(EffConnectServer.java:31)
[17:22:58 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:51)
[17:22:58 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[17:22:58 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[17:22:58 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[17:22:58 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:291)
[17:22:58 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:250)
[17:22:58 ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:248)
[17:22:58 ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:165)
[17:22:58 ERROR]: #!#!     at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
[17:22:58 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[17:22:58 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[17:22:58 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[17:22:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2013)
[17:22:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1832)
[17:22:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1785)
[17:22:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47)
[17:22:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5)
[17:22:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[17:22:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[17:22:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[17:22:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[17:22:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[17:22:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1132)
[17:22:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1125)
[17:22:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[17:22:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1086)
[17:22:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000)
[17:22:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173)
[17:22:58 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[17:22:58 ERROR]: #!#! 
[17:22:58 ERROR]: #!#! Version Information:
[17:22:58 ERROR]: #!#!   Skript: 2.5.3 (latest)
[17:22:58 ERROR]: #!#!     Flavor: skriptlang-github
[17:22:58 ERROR]: #!#!     Date: 2020-12-11
[17:22:58 ERROR]: #!#!   Bukkit: 1.16.5-R0.1-SNAPSHOT
[17:22:58 ERROR]: #!#!   Minecraft: 1.16.5
[17:22:58 ERROR]: #!#!   Java: 1.8.0_271 (Java HotSpot(TM) 64-Bit Server VM 25.271-b09)
[17:22:58 ERROR]: #!#!   OS: Windows Server 2019 amd64 10.0
[17:22:58 ERROR]: #!#! 
[17:22:58 ERROR]: #!#! Server platform: Paper
[17:22:58 ERROR]: #!#! 
[17:22:58 ERROR]: #!#! Current node: null
[17:22:58 ERROR]: #!#! Current item: [Skungee] EffConnectServer- Syntax: [[skungee] (send|connect) bungee[[ ]cord] [(player|uuid)[s]] %strings/players% to [bungee[[ ]cord]] [server[s]] %string% [with reason %-connectreason%], [skungee] (send|connect) [(player|uuid)[s]] %strings/players% to [bungee[[ ]cord]] server[s] %string% [with reason %-connectreason%]]
[17:22:58 ERROR]: #!#! Current trigger: command /hub (simple event) (hub command.sk, line -1)
[17:22:58 ERROR]: #!#! 
[17:22:58 ERROR]: #!#! Thread: Server thread
[17:22:58 ERROR]: #!#! 
[17:22:58 ERROR]: #!#! Language: english
[17:22:58 ERROR]: #!#! Link parse mode: DISABLED
[17:22:58 ERROR]: #!#! 
[17:22:58 ERROR]: #!#! End of Error.
[17:22:58 ERROR]: #!#!

**Comment by TheLimeGlass** [comment]
Duplicate #149
