### ISSUE TITLE
Async error message

### ISSUE THREAD

**Issue by Spartan9802** [Skungee/Skungee#241]
Hello,

Sending a message to the proxy doesn't work, I receive an error on the paperspigot server, I'm using the Skungee 1.0.15 version, can you fix it?
Thanks to you.

`
[16:02:45 WARN]: [Skungee] Task #1053 for Skungee v1.0.15 generated an exception
java.lang.IllegalStateException: SkungeeMessageEvent may only be triggered asynchronously.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:593) ~[patched_1.16.5.jar:git-Paper-469]
        at me.limeglass.skungee.spigot.sockets.SpigotPacketHandler.lambda$handlePacket$6(SpigotPacketHandler.java:216) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-469]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-469]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1294) ~[patched_1.16.5.jar:git-Paper-469]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.5.jar:git-Paper-469]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209) ~[patched_1.16.5.jar:git-Paper-469]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.5.jar:git-Paper-469]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-469]
        at java.lang.Thread.run(Thread.java:834) [?:?]
`

**Comment by ybadfg78** [comment]
I have that error too
