### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by dergrosehd** [Skungee/Skungee#247]
[11:15:30 INFO]: [Skungee] Charset US-ASCII does not support some symbols in script /home/Skriptbungee/Lobby/plugins/Skript/scripts/Teamchat.sk
[11:15:30 WARN]: java.nio.charset.MalformedInputException: Input length = 1
[11:15:30 WARN]:        at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
[11:15:30 WARN]:        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
[11:15:30 WARN]:        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
[11:15:30 WARN]:        at java.io.InputStreamReader.read(InputStreamReader.java:184)
[11:15:30 WARN]:        at java.io.BufferedReader.fill(BufferedReader.java:161)
[11:15:30 WARN]:        at java.io.BufferedReader.readLine(BufferedReader.java:324)
[11:15:30 WARN]:        at java.io.BufferedReader.readLine(BufferedReader.java:389)
[11:15:30 WARN]:        at java.nio.file.Files.readAllLines(Files.java:3205)
[11:15:30 WARN]:        at com.skungee.spigot.tasks.ServerDataTask.lambda$getScripts$0(ServerDataTask.java:53)
[11:15:30 WARN]:        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
[11:15:30 WARN]:        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
[11:15:30 WARN]:        at com.skungee.spigot.tasks.ServerDataTask.getScripts(ServerDataTask.java:47)
[11:15:30 WARN]:        at com.skungee.spigot.tasks.ServerDataTask.access$200(ServerDataTask.java:27)
[11:15:30 WARN]:        at com.skungee.spigot.tasks.ServerDataTask$2.toJson(ServerDataTask.java:88)
[11:15:30 WARN]:        at com.skungee.japson.shared.Japson.lambda$sendPacket$4(Japson.java:183)
[11:15:30 WARN]:        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
[11:15:30 WARN]:        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632)
[11:15:30 WARN]:        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[11:15:30 WARN]:        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[11:15:30 WARN]:        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[11:15:30 WARN]:        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)

It does this with every plugin I have, even though they shouldn't even have anything to do with Skungee, since they're just in the script folder.

**Comment by TheLimeGlass** [comment]
Version of Skungee? I'm assuming it's 2.0.0-ALPHA 16-17?

**Comment by Vayune** [comment]
No, it's 1.0.15 and I tried on 2.0.0 too and it's not working

**Comment by dergrosehd** [comment]
I don't know now which version it was, since I don't use this skungee anymore, but I downloaded the file 10 minutes before opening this issue.
