### ISSUE TITLE
Error in console while using "online/not online" statement

### ISSUE THREAD

**Issue by Vayune** [Skungee/Skungee#249]
Hi, if I use these strings:

every 2 seconds:
	if bungee server "Towny" is online:
		set {towny1} to "&3&l→ &cTowny:        "
		set {towny2} to "    &a%size of {playersintowny::*}%    "
	if bungee server "Towny" is not online:
		set {towny1} to "&c&l→ &8Towny&r        "
		set {towny2} to "  &4&lX"

They glitch my scoreboard made using Skbee and it shows an error in console:

[20:04:42 ERROR]: #!#!
[20:04:42 ERROR]: #!#! [Skript] Severe Error:
[20:04:42 ERROR]: #!#!
[20:04:42 ERROR]: #!#! Something went horribly wrong with Skript.
[20:04:42 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[20:04:42 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[20:04:42 ERROR]: #!#! Here is full list of them:
[20:04:42 ERROR]: #!#! skRayFall v1.9.24 (https://sk.rayfall.net/) skript-mirror v1.0.0 (https://github.com/btk5h/skript-mirror) Skungee v1.0.15 SkBee v1.10.2 (https://github.com/ShaneBeee/SkBee) Ersatz v1.0 Skellett v1.9.11 (https://forums.skunity.com/resources/skellett.24/)
[20:04:42 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[20:04:42 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[20:04:42 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[20:04:42 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[20:04:42 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[20:04:42 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[20:04:42 ERROR]: #!#!
[20:04:42 ERROR]: #!#! Stack trace:
[20:04:42 ERROR]: #!#! java.lang.NullPointerException
[20:04:42 ERROR]: #!#!     at me.limeglass.skungee.spigot.elements.conditions.CondServerOnline.check(CondServerOnline.java:21)
[20:04:42 ERROR]: #!#!     at ch.njol.skript.lang.Condition.run(Condition.java:55)
[20:04:42 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.walk(Conditional.java:50)
[20:04:42 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[20:04:42 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[20:04:42 ERROR]: #!#!     at ch.njol.skript.events.EvtPeriodical.execute(EvtPeriodical.java:94)
[20:04:42 ERROR]: #!#!     at ch.njol.skript.events.EvtPeriodical$1.run(EvtPeriodical.java:108)
[20:04:42 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[20:04:42 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[20:04:42 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1413)
[20:04:42 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:418)
[20:04:42 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1328)
[20:04:42 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1116)
[20:04:42 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289)
[20:04:42 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[20:04:42 ERROR]: #!#!
[20:04:42 ERROR]: #!#! Version Information:
[20:04:42 ERROR]: #!#!   Skript: 2.5.3 (latest)
[20:04:42 ERROR]: #!#!     Flavor: skriptlang-github
[20:04:42 ERROR]: #!#!     Date: 2020-12-11
[20:04:42 ERROR]: #!#!   Bukkit: 1.16.5-R0.1-SNAPSHOT
[20:04:42 ERROR]: #!#!   Minecraft: 1.16.5
[20:04:42 ERROR]: #!#!   Java: 1.8.0_281 (Java HotSpot(TM) 64-Bit Server VM 25.281-b09)
[20:04:42 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[20:04:42 ERROR]: #!#!
[20:04:42 ERROR]: #!#! Server platform: Paper
[20:04:42 ERROR]: #!#!
[20:04:42 ERROR]: #!#! Current node: null
[20:04:42 ERROR]: #!#! Current item: [Skungee] CondServerOnline- Syntax: [[bungee[[ ]cord]] server %string% (1¦is|2¦is(n't| not)) (running|online|responding)]
[20:04:42 ERROR]: #!#! Current trigger: every 2 seconds (every 2 seconds) (score.sk, line 4)
[20:04:42 ERROR]: #!#!
[20:04:42 ERROR]: #!#! Thread: Server thread
[20:04:42 ERROR]: #!#!
[20:04:42 ERROR]: #!#! Language: english
[20:04:42 ERROR]: #!#! Link parse mode: STRICT
[20:04:42 ERROR]: #!#!
[20:04:42 ERROR]: #!#! End of Error.
[20:04:42 ERROR]: #!#!
[20:04:44 ERROR]: #!#!
[20:04:44 ERROR]: #!#! [Skript] Severe Error:
[20:04:44 ERROR]: #!#!
[20:04:44 ERROR]: #!#! Something went horribly wrong with Skript.
[20:04:44 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[20:04:44 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[20:04:44 ERROR]: #!#! Here is full list of them:
[20:04:44 ERROR]: #!#! skRayFall v1.9.24 (https://sk.rayfall.net/) skript-mirror v1.0.0 (https://github.com/btk5h/skript-mirror) Skungee v1.0.15 SkBee v1.10.2 (https://github.com/ShaneBeee/SkBee) Ersatz v1.0 Skellett v1.9.11 (https://forums.skunity.com/resources/skellett.24/)
[20:04:44 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[20:04:44 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[20:04:44 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[20:04:44 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[20:04:44 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[20:04:44 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[20:04:44 ERROR]: #!#!
[20:04:44 ERROR]: #!#! Stack trace:
[20:04:44 ERROR]: #!#! java.lang.NullPointerException
[20:04:44 ERROR]: #!#!     at me.limeglass.skungee.spigot.elements.conditions.CondServerOnline.check(CondServerOnline.java:21)
[20:04:44 ERROR]: #!#!     at ch.njol.skript.lang.Condition.run(Condition.java:55)
[20:04:44 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.walk(Conditional.java:50)
[20:04:44 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[20:04:44 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[20:04:44 ERROR]: #!#!     at ch.njol.skript.events.EvtPeriodical.execute(EvtPeriodical.java:94)
[20:04:44 ERROR]: #!#!     at ch.njol.skript.events.EvtPeriodical$1.run(EvtPeriodical.java:108)
[20:04:44 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[20:04:44 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[20:04:44 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1413)
[20:04:44 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:418)
[20:04:44 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1328)
[20:04:44 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1116)
[20:04:44 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289)
[20:04:44 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[20:04:44 ERROR]: #!#!
[20:04:44 ERROR]: #!#! Version Information:
[20:04:44 ERROR]: #!#!   Skript: 2.5.3 (latest)
[20:04:44 ERROR]: #!#!     Flavor: skriptlang-github
[20:04:44 ERROR]: #!#!     Date: 2020-12-11
[20:04:44 ERROR]: #!#!   Bukkit: 1.16.5-R0.1-SNAPSHOT
[20:04:44 ERROR]: #!#!   Minecraft: 1.16.5
[20:04:44 ERROR]: #!#!   Java: 1.8.0_281 (Java HotSpot(TM) 64-Bit Server VM 25.281-b09)
[20:04:44 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[20:04:44 ERROR]: #!#!
[20:04:44 ERROR]: #!#! Server platform: Paper
[20:04:44 ERROR]: #!#!
[20:04:44 ERROR]: #!#! Current node: null
[20:04:44 ERROR]: #!#! Current item: [Skungee] CondServerOnline- Syntax: [[bungee[[ ]cord]] server %string% (1¦is|2¦is(n't| not)) (running|online|responding)]
[20:04:44 ERROR]: #!#! Current trigger: every 2 seconds (every 2 seconds) (score.sk, line 4)
[20:04:44 ERROR]: #!#!
[20:04:44 ERROR]: #!#! Thread: Server thread
[20:04:44 ERROR]: #!#!
[20:04:44 ERROR]: #!#! Language: english
[20:04:44 ERROR]: #!#! Link parse mode: STRICT
[20:04:44 ERROR]: #!#!
[20:04:44 ERROR]: #!#! End of Error.
[20:04:44 ERROR]: #!#!

Already using last version of everything.

**Comment by TheLimeGlass** [comment]
Duplicate #134 use Skungee 2.0.0 if you have a server with Skript 2.3+
