### ISSUE TITLE
When my server start, skungee event not works but when I /sk reload, all works.

### ISSUE THREAD

**Issue by 1stAlaix** [Skungee/Skungee#264]
```
[01:00:26 ERROR]: #!#!
[01:00:26 ERROR]: #!#! [Skript] Severe Error:
[01:00:26 ERROR]: #!#!
[01:00:26 ERROR]: #!#! Something went horribly wrong with Skript.
[01:00:26 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[01:00:26 ERROR]: #!#! Your Minecraft version or server software appears to be unsupported by Skript (bensku's version).
[01:00:26 ERROR]: #!#! Currently only supported servers are Spigot and its forks for Minecraft 1.9 or newer.
[01:00:26 ERROR]: #!#! Other versions might work, but since you're getting this error message something is NOT working,
[01:00:26 ERROR]: #!#! nor it will work, unless you switch to supported platform.
[01:00:26 ERROR]: #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues (only if you know what you're doing!)
[01:00:26 ERROR]: #!#!
[01:00:26 ERROR]: #!#! Stack trace:
[01:00:26 ERROR]: #!#! java.lang.NullPointerException
[01:00:26 ERROR]: #!#!     at me.limeglass.skungee.spigot.elements.effects.EffConnectServer.execute(EffConnectServer.java:31)
[01:00:26 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[01:00:26 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[01:00:26 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[01:00:26 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
[01:00:26 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:285)
[01:00:26 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:242)
[01:00:26 ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:257)
[01:00:26 ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:172)
[01:00:26 ERROR]: #!#!     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:00:26 ERROR]: #!#!     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[01:00:26 ERROR]: #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[01:00:26 ERROR]: #!#!     at java.lang.reflect.Method.invoke(Unknown Source)
[01:00:26 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
[01:00:26 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[01:00:26 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[01:00:26 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501)
[01:00:26 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486)
[01:00:26 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1186)
[01:00:26 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1006)
[01:00:26 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[01:00:26 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[01:00:26 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[01:00:26 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[01:00:26 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[01:00:26 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[01:00:26 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:807)
[01:00:26 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[01:00:26 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:746)
[01:00:26 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:644)
[01:00:26 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[01:00:26 ERROR]: #!#!
[01:00:26 ERROR]: #!#! Version Information:
[01:00:26 ERROR]: #!#!   Skript: 2.2-dev36 (custom version)
[01:00:26 ERROR]: #!#!   Bukkit: 1.8.8-R0.2-SNAPSHOT
[01:00:26 ERROR]: #!#!   Minecraft: 1.8.8
[01:00:26 ERROR]: #!#!   Java: 1.8.0_301 (Java HotSpot(TM) 64-Bit Server VM 25.301-b09)
[01:00:26 ERROR]: #!#!   OS: Windows Server 2019 amd64 10.0
[01:00:26 ERROR]: #!#!
[01:00:26 ERROR]: #!#! Server platform: Paper
[01:00:26 ERROR]: #!#!
[01:00:26 ERROR]: #!#! Current node: null
[01:00:26 ERROR]: #!#! Current item: [Skungee] EffConnectServer- Syntax: [[skungee] (send|connect) bungee[[ ]cord] [(player|uuid)[s]] %strings/players% to [bungee[[ ]cord]] [server[s]] %string% [with reason %-connectreason%], [skungee] (send|connect) [(player|uuid)[s]] %strings/players% to [bungee[[ ]cord]] server[s] %string% [with reason %-connectreason%]]
[01:00:26 ERROR]: #!#! Current trigger: command /build (simple event) (Hub.sk, line -1)
[01:00:26 ERROR]: #!#!
[01:00:26 ERROR]: #!#! Thread: Server thread
[01:00:26 ERROR]: #!#!
[01:00:26 ERROR]: #!#! Language: english
[01:00:26 ERROR]: #!#! Link parse mode: DISABLED
[01:00:26 ERROR]: #!#!
[01:00:26 ERROR]: #!#! End of Error.
[01:00:26 ERROR]: #!#!
>


Version
[01:00:26 ERROR]: #!#!   Skript: 2.2-dev36 (custom version)
[01:00:26 ERROR]: #!#!   Bukkit: 1.8.8-R0.2-SNAPSHOT
[01:00:26 ERROR]: #!#!   Minecraft: 1.8.8
[01:00:26 ERROR]: #!#!   Java: 1.8.0_301 (Java HotSpot(TM) 64-Bit Server VM 25.301-b09)
Skungee version 1.0.15 by Skungee
I use FlameCord for the bungeecord and mSpigot.

Thanks for your helping.
```

**Comment by TheRemiDev** [comment]
I have exactly the same problem. I don't have any solutions at the moment.
