### ISSUE TITLE
java.lang.IllegalStateException: Asynchronous command dispatch!

### ISSUE THREAD

**Issue by domasbug** [Skungee/Skungee#53]
`[18:37:05 WARN]: java.lang.IllegalStateException: Asynchronous command dispatch!
[18:37:05 WARN]:        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15)
[18:37:05 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:707)
[18:37:05 WARN]:        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:655)
[18:37:05 WARN]:        at ch.njol.skript.Skript.dispatchCommand(Skript.java:1317)
[18:37:05 WARN]:        at ch.njol.skript.effects.EffCommand.execute(EffCommand.java:84)
[18:37:05 WARN]:        at ch.njol.skript.lang.Effect.run(Effect.java:52)
[18:37:05 WARN]:        at me.limeglass.skungee.spigot.sockets.SpigotPacketHandler.handlePacket(SpigotPacketHandler.java:96)
[18:37:05 WARN]:        at me.limeglass.skungee.spigot.sockets.SpigotRunnable.run(SpigotRunnable.java:85)
[18:37:05 WARN]:        at java.lang.Thread.run(Thread.java:748)`

CODE: `skungee evaluate skript code "console command ""%arg-2%""" on the bungee cord servers arg-1`

I am executing this command from Lobby, everything works on 1.8 servers, but It doesn't works on 1.13.2 server.

**Comment by TheLimeGlass** [comment]
Fixed in 1.0.9b, thanks for the bug report 👍
