### ISSUE TITLE
Resourcepack error in the console on Bungeecord

### ISSUE THREAD

**Issue by Tyberhertz** [Skungee/Skungee#65]
I currently have a problem with Skungee:
the error code is on logfile from Bungeecord - Waterfall

Bungeecord: waterfall
skungee: 1.0.9
BungeeResourcepacks: 1.6.19-SNAPSHOT (build 272)

[20:19:44 ERROR]: java.lang.UnsupportedOperationException: Unsupported handler type!
[20:19:44 ERROR]: at de.themoep.resourcepacksplugin.bungee.packets.ResourcePackSendPacket.handle(ResourcePackSendPacket.java:100)
[20:19:44 ERROR]: at me.limeglass.skungee.bungeecord.protocol.channel.ChannelHandler.write(ChannelHandler.java:25)
[20:19:44 ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:706)
[20:19:44 ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:698)
[20:19:44 ERROR]: at io.netty.channel.AbstractChannelHandlerContext.access$1700(AbstractChannelHandlerContext.java:38)
[20:19:44 ERROR]: at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1091)
[20:19:44 ERROR]: at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1138)
[20:19:44 ERROR]: at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1062)
[20:19:44 ERROR]: at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[20:19:44 ERROR]: at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[20:19:44 ERROR]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:333)
[20:19:44 ERROR]: at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
[20:19:44 ERROR]: at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by TheLimeGlass** [comment]
The issue is from the plugin `resourcepacksplugin`

`java.lang.UnsupportedOperationException: Unsupported handler type!`
