### ISSUE TITLE
ConcurrentModificationException within the BungeeSockets

### ISSUE THREAD

**Issue by Allesco** [Skungee/Skungee#68]
https://pastebin.com/3sQSK9Ba

Skungee can't connect and spams the whole time.

**Comment by TheLimeGlass** [comment]
Are you putting the port of the Bungeecord or the server? I will need your credentials to figure out more.

**Comment by TheLimeGlass** [comment]
This is a bug though ```
Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@1efe439d, id=1194, owner=me.limeglass.skungee.bungeecord.Skungee@2f08c4b, task=me.limeglass.skungee.bungeecord.sockets.BungeeSockets$2@21a42843, delay=0, period=0, running=true) encountered an exception
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)
    at java.util.HashMap$KeyIterator.next(HashMap.java:1469)
    at me.limeglass.skungee.bungeecord.sockets.BungeeSockets$2.run(BungeeSockets.java:139)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by TheLimeGlass** [comment]
What version are you using of Skungee?

**Comment by TheLimeGlass** [comment]
You can now bind an address to an IP in the newest versions, will help your issue.

**Comment by TheLimeGlass** [comment]
```
>.... [18:59:34 INFO]: [nUKEmAN4|/myip:myport] <-> ServerConnector [Lobby-1] has disconnected
>.... [18:59:34 ERROR]: Exception in thread "Thread-13" Exception in thread "Thread-17" java.util.ConcurrentModificationException
>.... [18:59:34 ERROR]: at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)
>.... [18:59:34 ERROR]: at java.util.HashMap$ValueIterator.next(HashMap.java:1474)
>.... [18:59:34 ERROR]: at java.util.AbstractCollection.remove(AbstractCollection.java:292)
>.... [18:59:34 ERROR]: at net.md_5.bungee.api.plugin.PluginManager.unregisterCommands(PluginManager.java:109)
>.... [18:59:34 ERROR]: at me.limeglass.skungee.bungeecord.handlers.executors.UnregisterCommandsHandler.executePacket(UnregisterCommandsHandler.java:25)
>.... [18:59:34 ERROR]: at me.limeglass.skungee.bungeecord.handlercontroller.SkungeeExecutor.handlePacket(SkungeeExecutor.java:22)
>.... [18:59:34 ERROR]: at me.limeglass.skungee.bungeecord.sockets.BungeeRunnable.run(BungeeRunnable.java:118)
>.... [18:59:34 ERROR]: at java.lang.Thread.run(Thread.java:748)
>.... [18:59:34 ERROR]: java.util.ConcurrentModificationException
>.... [18:59:34 ERROR]: at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
>.... [18:59:34 ERROR]: at java.util.ArrayList$Itr.remove(ArrayList.java:873)
>.... [18:59:34 ERROR]: at com.google.common.collect.AbstractMapBasedMultimap$WrappedCollection$WrappedIterator.remove(AbstractMapBasedMultimap.java:494)
>.... [18:59:34 ERROR]: at net.md_5.bungee.api.plugin.PluginManager.unregisterCommands(PluginManager.java:110)
>.... [18:59:34 ERROR]: at me.limeglass.skungee.bungeecord.handlers.executors.UnregisterCommandsHandler.executePacket(UnregisterCommandsHandler.java:25)
>.... [18:59:34 ERROR]: at me.limeglass.skungee.bungeecord.handlercontroller.SkungeeExecutor.handlePacket(SkungeeExecutor.java:22)
>.... [18:59:34 ERROR]: at me.limeglass.skungee.bungeecord.sockets.BungeeRunnable.run(BungeeRunnable.java:118)
>.... [18:59:34 ERROR]: at java.lang.Thread.run(Thread.java:748)
>.... [18:59:34 INFO]: [Skungee] Connected to server Lobby-1 with port mylobbyport
```

**Comment by TheLimeGlass** [comment]
Can't replicate, if you can still replicate, please make a new issue.
