### ISSUE TITLE
3.6 million lines skungee error

### ISSUE THREAD

**Issue by MrnonSwag** [Skungee/Skungee#74]
Hey,
I have a decent big console bug... would be cool if someone could help me.
error #51  and #61  do not bring any solution

i can't paste the error here (40MB/3600000 lines)

**Comment by TheLimeGlass** [comment]
just post the part where it stops duplicating.

**Comment by MrnonSwag** [comment]
[06:28:02] [Server thread/ERROR]: Couldn't save chunk; already in use by
another instance of Minecraft?
net.minecraft.server.v1_8_R3.ExceptionWorldConflict: Failed to check
session lock for world located at ./Lobby, aborting. Stop the server and
delete the session.lock in this world to prevent further issues.
at
net.minecraft.server.v1_8_R3.WorldNBTStorage.checkSession(WorldNBTStorage.java:79)
~[Spigot.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.World.checkSession(World.java:2824)
~[Spigot.jar:git-Spigot-db6de12-18fbb24]
at
net.minecraft.server.v1_8_R3.ChunkRegionLoader.a(ChunkRegionLoader.java:120)
~[Spigot.jar:git-Spigot-db6de12-18fbb24]
at
net.minecraft.server.v1_8_R3.ChunkProviderServer.saveChunk(ChunkProviderServer.java:251)
[Spigot.jar:git-Spigot-db6de12-18fbb24]
at
net.minecraft.server.v1_8_R3.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:357)
[Spigot.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:234)
[Spigot.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:770)
[Spigot.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[Spigot.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[Spigot.jar:git-Spigot-db6de12-18fbb24]
at
net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[Spigot.jar:git-Spigot-db6de12-18fbb24]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
[06:28:03] [Craft Scheduler Thread - 2/INFO]:
[06:28:03] [Craft Scheduler Thread - 2/INFO]: [Skungee] [Skungee] Severe
Error:
[06:28:03] [Craft Scheduler Thread - 2/INFO]: [Skungee] Socket couldn't be
accepted.
[06:28:03] [Craft Scheduler Thread - 2/INFO]:
[06:28:03] [Craft Scheduler Thread - 2/INFO]: [Skungee] Something went
wrong within Skungee.
[06:28:03] [Craft Scheduler Thread - 2/INFO]: [Skungee] Please report this
error to the developers of Skungee so we can fix this from happening in the
future.
[06:28:03] [Craft Scheduler Thread - 2/INFO]:
[06:28:03] [Craft Scheduler Thread - 2/INFO]: [Skungee] Report this at
https://github.com/TheLimeGlass/Skungee/issues
[06:28:03] [Craft Scheduler Thread - 2/INFO]: [Skungee] You can also
message one of the Skungee developers this error.
[06:28:03] [Craft Scheduler Thread - 2/INFO]:
[06:28:03] [Craft Scheduler Thread - 2/INFO]: [Skungee] Stack trace:
[06:28:03] [Craft Scheduler Thread - 2/INFO]: [Skungee]
java.net.SocketException: Too many open files (Accept failed)
[06:28:03] [Craft Scheduler Thread - 2/INFO]: [Skungee]     at
java.net.PlainSocketImpl.socketAccept(Native Method)
[06:28:03] [Craft Scheduler Thread - 2/INFO]: [Skungee]     at
java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
[06:28:03] [Craft Scheduler Thread - 2/INFO]: [Skungee]     at
java.net.ServerSocket.implAccept(ServerSocket.java:545)
[06:28:03] [Craft Scheduler Thread - 2/INFO]: [Skungee]     at
java.net.ServerSocket.accept(ServerSocket.java:513)
[06:28:03] [Craft Scheduler Thread - 2/INFO]: [Skungee]     at
me.limeglass.skungee.spigot.sockets.Reciever$1.run(Reciever.java:44)
[06:28:03] [Craft Scheduler Thread - 2/INFO]: [Skungee]     at
org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[06:28:03] [Craft Scheduler Thread - 2/INFO]: [Skungee]     at
org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[06:28:03] [Craft Scheduler Thread - 2/INFO]: [Skungee]     at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[06:28:03] [Craft Scheduler Thread - 2/INFO]: [Skungee]     at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[06:28:03] [Craft Scheduler Thread - 2/INFO]: [Skungee]     at
java.lang.Thread.run(Thread.java:748)

Am Do., 29. Aug. 2019 um 10:27 Uhr schrieb LimeGlass <
notifications@github.com>:

**Comment by MrnonSwag** [comment]
I have already deleted the session.loc several times but brought no
improvements

Am Do., 29. Aug. 2019 um 13:09 Uhr schrieb MrNonSwag <
mrminecraft00@googlemail.com>:

**Comment by TheLimeGlass** [comment]
Duplicate https://github.com/Skungee/Skungee/issues/55

**Comment by MrnonSwag** [comment]
error #51 and #61 do not bring any solution
