### ISSUE TITLE
Skungee always throwing error on startup (bungee-side)

### ISSUE THREAD

**Issue by Govindass** [Skungee/Skungee#83]
since I updated to newer version of Skungee which you released today (and which I'm super happy to see as Skungee is pretty unreplaceable addon!), it keeps throwing this error, even if I change port to another (which is definitely not in use as I checked what ports are in use before startup) I also tried 1337 and 25551, all threw the same error with port being the only difference.
[09:46:33 INFO]: [Skungee] [Skungee] Severe Error: [ServerSocket couldn't be created on port: 1335]
[09:46:33 INFO]:
[09:46:33 INFO]: [Skungee] Something went wrong within Skungee.
[09:46:33 INFO]: [Skungee] Please report this error to the developers of Skungee so we can fix this from happening in the future.
[09:46:33 INFO]:
[09:46:33 INFO]: [Skungee] Report this at https://github.com/TheLimeGlass/Skungee/issues. You can also message one of the Skungee developers.
[09:46:33 INFO]:
[09:46:33 INFO]: [Skungee] Stack trace:
[09:46:33 INFO]: [Skungee] java.net.SocketException: Already bound
[09:46:33 INFO]: [Skungee]     at java.net.ServerSocket.bind(ServerSocket.java:361)
[09:46:33 INFO]: [Skungee]     at java.net.ServerSocket.bind(ServerSocket.java:329)
[09:46:33 INFO]: [Skungee]     at me.limeglass.skungee.bungeecord.Skungee.connect(Skungee.java:149)
[09:46:33 INFO]: [Skungee]     at me.limeglass.skungee.bungeecord.Skungee.onEnable(Skungee.java:81)
[09:46:33 INFO]: [Skungee]     at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:283)
[09:46:33 INFO]: [Skungee]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:281)
[09:46:33 INFO]: [Skungee]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
[09:46:33 INFO]: [Skungee]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
[09:46:33 INFO]:
[09:46:33 INFO]: [Skungee] Information:
[09:46:33 INFO]: [Skungee]   Skungee: 1.0.10
[09:46:33 INFO]: [Skungee]   Bungee: git:Waterfall-Bootstrap:1.14-SNAPSHOT:c3d67e5:290
[09:46:33 INFO]: [Skungee]   Game version: 1.8.x, 1.9.x, 1.10.x, 1.11.x, 1.12.x, 1.13.x, 1.14.x
[09:46:33 INFO]: [Skungee]   Protocol version: 498
[09:46:33 INFO]: [Skungee]   Java: 1.8.0_211 (Java HotSpot(TM) 64-Bit Server VM 25.211-b12)
[09:46:33 INFO]: [Skungee]   OS: Linux amd64 3.16.0

**Comment by Govindass** [comment]
the problem was solved after putting "localhost" in skungee config, previously on older version I used my server's ip in it, which used to work well, but this update broke it, so I guess issue is solved
