### ISSUE TITLE
Events not being defined as async events on Spigot

### ISSUE THREAD

**Issue by ham1255** [Skungee/Skungee#84]
as related to #63 thats is being fixed error still going 
```
>.... [11:42:28 WARN]: Exception in thread "Thread-52" java.lang.IllegalStateException: SkungeePingEvent may only be triggered synchronously.
>.... [11:42:28 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:533)
>.... [11:42:28 WARN]: at me.limeglass.skungee.spigot.sockets.SpigotPacketHandler.handlePacket(SpigotPacketHandler.java:201)
>.... [11:42:28 WARN]: at me.limeglass.skungee.spigot.sockets.SpigotRunnable.run(SpigotRunnable.java:91)
>.... [11:42:28 WARN]: at java.lang.Thread.run(Thread.java:748)
```

**Comment by ham1255** [comment]
like every event in skungee make this error

**Comment by TheLimeGlass** [comment]
Please provide the version you are using.

**Comment by ham1255** [comment]
1.0.10 on 1.14.4

**Comment by ham1255** [comment]
made pull request check it out
