### ISSUE TITLE
Can't get server of a player + Can't send skungee messages to players

### ISSUE THREAD

**Issue by Govindass** [Skungee/Skungee#94]
using send "%skungee ""Govindas"" bungee server%" returns "None", while I am online
then using skungee message "hello" to bungeecord player "Govindas" says unknown syntax, only started happening after updating from 1.0.10 to 1.0.11

also using skungee message "a" to bungee players
throws this error:
[11:19:41 ERROR]: #!#! Stack trace:
[11:19:41 ERROR]: #!#! java.lang.ArrayIndexOutOfBoundsException: 1
[11:19:41 ERROR]: #!#!     at me.limeglass.skungee.spigot.lang.ExpressionData.get(ExpressionData.java:100)
[11:19:41 ERROR]: #!#!     at me.limeglass.skungee.spigot.elements.effects.EffMessagePlayers.execute(EffMessagePlayers.java:25)
[11:19:41 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[11:19:41 ERROR]: #!#!     at ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:283)
[11:19:41 ERROR]: #!#!     at ch.njol.skript.command.Commands$3$1.call(Commands.java:216)
[11:19:41 ERROR]: #!#!     at ch.njol.skript.command.Commands$3$1.call(Commands.java:1)
[11:19:41 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftFuture.run(CraftFuture.java:85)
[11:19:41 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423)
[11:19:41 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840)
[11:19:41 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[11:19:41 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[11:19:41 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[11:19:41 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)

**Comment by TheLimeGlass** [comment]
Duplicate #93

**Comment by Govindass** [comment]
not exactly duplicate I think, as that one doesn't contain server part
